# -*- coding: utf-8 -*-
"""CodeLeague21-Round1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mAcJuPYAaZpURnnoTS3G0NUoQ5nEZBDv
"""

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from google.colab import drive
drive.mount('/content/drive/')

contacts = pd.read_json('/content/drive/My Drive/contacts.json')
contacts.head(10)

import numpy
import datetime
time_start = datetime.datetime.now()

memory = {}
cluster = {}
contacts_dict = {}
result = {}
def add_to_memory(user_id, value):
  if(value != ''):
    if(value in memory):
      memory[value].add(user_id)
      return
    
    memory[value] = {user_id}

def add_to_cluster(user_id, email, phone, orderid, contacts):
  ids = set()
  cluster[user_id] = {100000000}
  if(email in memory and email != ''):
    ids.update(memory[email])
  if(phone in memory and phone != ''):
    ids.update(memory[phone])
  if(orderid in memory and orderid != ''):
    ids.update(memory[orderid])
  for i in ids:
    cluster[user_id].add(i)
  cluster[user_id].remove(100000000)
  contacts_dict[user_id] = {contacts}

for row in contacts.values:
  id = row[0]
  add_to_memory(id, row[4])
  add_to_memory(id, row[1])
  add_to_memory(id, row[2])

for row in contacts.values:
  add_to_cluster(row[0], row[1], row[2], row[4], row[3])

for key, value in cluster.items():
  ids = set(value)
  new_ids = set()
  jumlah_contact = 0
  for id in ids:
    new_ids.update(cluster[id])
  
  susun_string = ""
  for id in sorted(new_ids):
    cluster[id] = sorted(new_ids)

for key, value in cluster.items():
  jumlah_contact = 0
  str_result = ""
  for ids in cluster[key]:
    jumlah = list(contacts_dict[ids])[0]
    jumlah_contact += jumlah
    str_result += str(ids)+'-'
  str_result = str_result[:-1]+", "+str(jumlah_contact)
  result[key] = {str_result}

time_end = datetime.datetime.now()
time_range = time_end - time_start
print("Proses berjalan selama: "+str(time_range))

print(result[0])
print(result[1])
print(result[2])
print(result[3])
print(result[4])
print(result[5])
print(result[6])
print(result[7])
print(result[8])
print(result[9])

print(contacts.iloc[1])
print("\n")
print(contacts.iloc[2458])
print("\n")
print(contacts.iloc[98519])
print("\n")
print(contacts.iloc[115061])
print("\n")
print(contacts.iloc[140081])
print("\n")
print(contacts.iloc[165605])
print("\n")
print(contacts.iloc[476346])
print("\n")